@startuml

' Définition des classes avec ajustements selon les recommandations
class Jeu {
    - Stopwatch ChronometreJoueur
    - int tempsTour
    - int nombreTours
    - List<Joueur> listeJoueurs
    - int taillePlateau
    + List<Joueur> ListeJoueurs
    + Main(string[] arg)
    - InitialisationJeu()
    - BoucleDeJeu()
    - FinDuJeu()
}

class Joueur {
    - string nom
    - int score
    - Dictionary<string, int> mots
    + string Nom
    + int Score
    + Dictionary<string, int> Mots
    + AjouterMot(string mot)
    + Contains(string mot)
    + ToString()
}

class Plateau {
    - De[,] plateau
    - List<string> motsTrouves
    + Initialisation(int taille)
    + Lance()
    + TestMot(string mot)
    + Contains(string mot)
    + toString(): string
}

class Dictionnaire {
    - SortedDictionary<int, string[]> motsParLongueur
    - SortedDictionary<char, string[]> motsParLettre
    + Initialisation()
    + Contains(string mot): bool
    + RechDichoRecursif(string mot): bool
}

class De {
    - char[] faces
    - char faceVisible
    + char FaceVisible
    + Lance(Random r)
    + ToString(): string
}

class NuageDeMots {
    + GenererNuageDeMots(Dictionary<string, int> mots, string nom)
}

class Langue {
    - SortedList<char, int> pointsParLettre
    - SortedList<char, int> occurrencesMaxParLettre
    - char[] probabilitesLettres
    + string CodeLangue
    + Initialisation(string langue)
    + ObtenirLettreParProbabilite(int proba)
}

' Relations entre les classes
Jeu "1" *-- "2..*" Joueur
Jeu "1" *-- "1" Plateau
Langue "1" ..> "1" Plateau
Jeu "1" *-- "1" Dictionnaire
Langue "1" ..> "1" Dictionnaire
Langue "1" ..> "1" De
Plateau "1" *-- "1..*" De
Joueur "1" *-- "1" NuageDeMots

@enduml